l10n: zh_CN: updated translation for 2.47
git-l10n/git-po pull request #798
Opened 2024-10-04 18:58 UTC by dyrone

Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use GitGitGadget (https://gitgitgadget.github.io/)
to conveniently send your Pull Requests commits to our mailing list.

For a single-commit pull request, please *leave the pull request description
empty*: your commit message itself should describe your changes.

Please read the "guidelines for contributing" linked above!

2024-10-05 13:31 UTC, lilydjwg requested changes

2024-10-05 13:31 UTC, lilydjwg commented on po/zh_CN.po
> +msgstr "在后台执行运维"
```suggestion
msgstr "在后台进行维护"
```

2024-10-05 13:31 UTC, lilydjwg commented on po/zh_CN.po
> +msgstr "如若应在克隆期间获取标签则指定"
```suggestion
msgstr "指定是否在克隆期间获取标签"
```

2024-10-06 03:41 UTC, merged

2024-10-06 12:21 UTC, jiangxin commented
@dyrone 评审中的 PR 请设置为草稿状态，待评审问题全部解决再设置为可合并状态。
未完成的修改请放到你自己仓库中，待下次本地化窗口开启再合入。